### ISSUE TITLE
Cannot handle error when authorization key is invalid

### ISSUE THREAD

**Issue by rhussmann** [splitio/javascript-client#106]
## Issue
Is it possible to detect when an invalid auth key is provided during initialization? Consider the code below.

```javascript
var splitio = require('@splitsoftware/splitio');

var factory = splitio({
  core: {
    authorizationKey: 'THIS_IS_NOT_A_REAL_KEY'
  }
});

var client = factory.client();
```

This will ultimately result in:
```
(node:67546) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Not Found
```

I have tried the following to capture the error:
* Listen for the `SDK_READY_TIMEOUT` event, and
* try client.ready().catch()

The former event never fires, and the later `catch()` also never fires and `client.ready()` is deprecated.

What is the correct way to detect the auth failure above?

**Comment by NicoZelaya** [comment]
Hi! Hope you're having a good day and sorry to hear you're having issues with the SDK. 

I'm taking a look into this, could you provide some more information about your setup? Are you testing on Nodejs or the browser? which version? 

To answer your question yes, the correct way would be to wait for an SDK_READY_TIMEOUT event. If we have an issue we'll take care and let you know!

**Comment by NicoZelaya** [comment]
@rhussmann I see what's going on. There's a mistake on a section of our docs that does not mention the startup settings for Node, most importantly, the default value for timeout. 

On NodeJS the startup timeout time is 0, which means no timeout. You can do this for the SDK to timeout after an `X` amount of time:

`var sdk = splitio({
  core: {
    authorizationKey: 'FAKE_KEY'
  },
  startup: {
    readyTimeout: X
  }
});` 

After the X amount of time passes if the SDK is not yet ready, no matter the reason, you'll get the timeout event. Please let us know if you have everything you need.

We'll fix the docs, thanks again for letting us know!

**Comment by rhussmann** [comment]
@NicoZelaya Thanks! I am indeed using the SDK in node.js.

The doc update would be great. Additionally, please specify in the docs what the unit is for `readyTimeout` e.g. seconds, milliseconds, etc.

Thanks again. I'll close this issue once I can verify in my setup.

**Comment by NicoZelaya** [comment]
Sorry for not pointing out that detail, the unit is seconds.

Hope everything works as expected!

**Comment by NicoZelaya** [comment]
@rhussmann I'll go ahead and close the issue for now. Feel free to create a new one if you're still having problems!

**Comment by rhussmann** [comment]
@NicoZelaya This did address my issue. Thank you.
