### ISSUE TITLE
Process is not defined

### ISSUE THREAD

**Issue by bryanjjohnson** [splitio/javascript-client#162]
After upgrading our project to Angular 6, we now get this error
`Uncaught ReferenceError: process is not defined
    at Object../node_modules/@splitsoftware/splitio/es/utils/logger/index.js (index.js:28)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/@splitsoftware/splitio/es/utils/manager/validate.js (validate.js:1)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/@splitsoftware/splitio/es/manager/index.js (main.js:65475)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/@splitsoftware/splitio/es/index.js (main.js:65347)
    at __webpack_require__ (bootstrap:81)`

After digging around, it seems like Angular-cli team made some changes that would break certain libraries: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814
> We understand that this isn't great if your code relies, directly or indirectly, on a library that makes incorrect assumptions about browser environments. The best I can say is that you should bring this problem to their attention via an issue on their tracker. Maybe newer versions of that library don't have this behaviour anymore.

**Comment by NicoZelaya** [comment]
Hi Bryan! Hope you're having a great day.

First of all, thank you so much for flagging! Sorry to hear you're having issues with the SDK, but I'm able to reproduce it using an example application and will be addressing it shortly. 

I'll keep you posted here once we have a release candidate in case you want to try that, as well as whenever we release the corresponding stable version. 

Our apologies for the inconveniences.
Best,
Nico Zelaya.

**Comment by NicoZelaya** [comment]
Hi Bryan! Quick update, we've released a release candidate version to npm with a fix for this. It was tested using the latest @angular/cli version (among other tools & frameworks) and it seems to work as expected. 

If you want to give it a try, the version is `10.3.2-canary.0` which you can install that by running `npm i -S @splitsoftware/splitio@10.3.2-canary.0`

We expect to release it as a stable version early next week. I'll update you here when that happens, so let's keep this open for now.

Best,
Nico.

**Comment by NicoZelaya** [comment]
Hello again,

we've released the stable version `10.3.2` which should address this, if you want to give it a try. Closing the issue, but please let us know how it went!

Best,
Nico

**Comment by bryanjjohnson** [comment]
That worked. Thanks!
