### ISSUE TITLE
node.js documentation on site for getTreatment and getTreatments is wrong

### ISSUE THREAD

**Issue by jmurretxactly** [splitio/javascript-client#192]
https://docs.split.io/docs/javascript-sdk-overview

The documentation reflects this function signatures:
getTreatment(splitName, attributes)
getTreatments(splitNames, attributes)

This is only true for browser SDK version.

Non-browser SDK version has this: 
getTreatment(key, splitName, attributes)
getTreatments(key, splitNames, attributes)

**Comment by NicoZelaya** [comment]
Hey @jmurretxactly ! 

We have the documentation for NodeJS/Node-like environments here: https://docs.split.io/docs/nodejs-sdk-overview

I'll make sure to mention this to the team in case we can make a clearer statement that those documentations are separated. Maybe we could add a mention and a link on the "Language Support" section right at the top. 

Thank you for flagging! And if you have any other comments about our docs, you're more than welcome. If not, I'll close the issue later.

Best,
Nico Zelaya.

**Comment by NicoZelaya** [comment]
Already mentioned to the team in charge of documentation.

Closing since no more updates and not a library issue. Thank you again for flagging! 

Best,
Nico Zelaya.
