### ISSUE TITLE
403 Errors after updating to v10.4.0

### ISSUE THREAD

**Issue by rossPatton** [splitio/javascript-client#215]
Hey,

So I was excited for the size decreases in 10.4.0 and decided to upgrade. However, now I am getting 403s locally. Before, I was not getting any errors with my setup. I am assuming it is due to this change => `Bugfixing - Capturing uncaught exception on some http and network errors.`

What exactly changed here that would result in a working setup suddently 403ing locally? This error only comes up on the server side, on client, things continue to work fine

Here is the error:

```
[1] (node:79725) UnhandledPromiseRejectionWarning: Error: 403 - Forbidden operation. Check API key permissions.
[1]     at /path/to/project/node_modules/@splitsoftware/splitio/lib/services/transport/index.js:61:11
[1]     at <anonymous>
[1]     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[1] (node:79725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

Thanks

**Comment by NicoZelaya** [comment]
Hey Ross! 

Really sorry to hear you're having inconveniences. I think it would be best to talk about this through our support platform, so unless you can resolve it I would suggest that you send an email to support@split.io where we can speak more fluidly while protecting your data.

Nevertheless, there are some things that we can check if you still have problems once you resolve the default value thing. If you're getting 403's it means that your API Key does not have the necessary permissions. 

- Is the API Key you're using on the server side of type `sdk` ? The ones of type browser would work fine there but will throw 403's on Node when trying to download segments data.
- Could you confirm that the API Key was not revoked and it's still valid? You can check that on your Admin dashboard on [app.split.io](https://app.split.io)

The change you're highlighting was just ensuring we capture all those exceptions so we can throw the correct message to you using our logs. We had few cases where the exception was just bubbling all the way up with an awful `Uncaught promise rejection(undefined)` message after we added `axios` for issuing HTTP requests. 

Going back to your question, is it possible that something changed on your side and before you were not falling back to the default key? 
Seems unlikely that you were not getting 403's before with the same scenario and that would had meant that the SDK was never ready, so you would have seen at least that behaviour. (Besides throwing a bunch of error logs).
The only thing that comes to mind would be if you were not checking for SDK readiness nor handling readiness timeout, also using an API Key of type Browser. If that was your case maybe you were able to use Splits but without having the Segments (which I guess you are not using much).

Last but not least, if you have the chance, I would suggest that you update directly to 10.5.1 which is our latest stable version. 

Again, sorry for the inconveniences and thank you for reaching out! Feel free to reply here if you need help with code but if we need to talk more in depth about your case I strongly suggest you open a support ticket, I'll be happy to keep working with you there with more tools available.

Best regards,
Nico.
