### ISSUE TITLE
Don't use axios globally

### ISSUE THREAD

**Issue by kfoxb** [splitio/javascript-client#230]
In my project, I've set up an interceptor for Axios to add a token to every request. Because the transport service in this SDK is using Axios globally it also used my interceptor and added a token to requests resulting in 404's.

I changed my interceptor to use an instance of Axios, but I wanted to open this issue to let you know you should probably do the same so that this doesn't happen to other people that do want to use Axios globally.

You can see what I mean by Axios instance here: https://www.npmjs.com/package/axios#creating-an-instance.

**Comment by NicoZelaya** [comment]
Hey @kfoxb ! 

First of all, thank you for calling that out! I'm sorry for both the inconveniences and the delay on my response here, it was a busy week. 

What you're saying makes total sense, I'll make sure we create a ticket and include the update as part of our upcoming releases. 

Again, thanks for reaching out! I'll close the issue for now but feel free to reopen if needed.
Best,
Nico.

**Comment by kfoxb** [comment]
Awesome, thank you very much @NicoZelaya :-)
