### ISSUE TITLE
Have a way to override localhost feature mock in console

### ISSUE THREAD

**Issue by jasonkim** [splitio/javascript-client#247]
In localhost mode, it expects features mock for setting the values it checks for. In order to change on/off, it requires code change. Often that is not convenient. It would be awesome to have a way to quickly set it in the console.

**Comment by NicoZelaya** [comment]
Hi @jasonkim ! 

First of all, sorry for the delay on my response here. Could you share some more data around your tests? Are you running it on Node (using the file) or on Browsers (using the map) ?

For Node~ish tests, you should be able to update the treatment you want on the mock file, wait for the updater to check it and changes will propagate.

For Browser~ish tests, you need to modify the object you're sending to the config, without loosing the reference to it if possible. In any case, the updater checks whatever map you have on the `features` prop of the SDK config and updates the mocks accordingly.
As long as you keep a reference to the config, you should be fine. If you want to do it from the console you can expose it yourself to the global environment.

For both cases, the `scheduler.offlineRefreshRate` setting controls the updater check schedule.

Let me know if you still need help with it and I'll be happy to help you setup your tests!

Best,
Nico.

**Comment by jasonkim** [comment]
I am using the browser.
I didn't realize I could change the config after the fact with a reference to the config. That seems like a handy thing to point out in the doc (maybe I missed it...?).
I haven't tried it and will try it out and let you know.

**Comment by NicoZelaya** [comment]
Thanks Jason for pointing that out! I'm checking the docs and it mentions you can change them but without any explanation on how to do it/how it works. I'll sync with the team so we update those.

Either way I'll wait for your confirmation before closing the issue.

**Comment by jasonkim** [comment]
I'm sorry it took a while to test this out, but got to this today.
So I've tried to change the config map after and calling `getTreatment()`. It didn't get updated and I've tested it long after that it should have taken a hold.
My setup code is as follows (slightly modified to expose the vars globally).
```
window.splitconfig = {
  test: 'stuff',
}

export const splitFactory = SplitFactory({
  core: {
    authorizationKey: apiKey,
    key: 'anonymous',
  },
  // Use below to override dev mode(localhost)
  features: window.splitconfig,
})

// Store and reuse split clients per id
const splitClients = {}
window.splitclients = splitClients
export function splitClient(id) {
  splitClients[id] = splitClients[id] || splitFactory.client(id)
  return splitClients[id]
}
```

I then changed the `splitconfig` in the console and called `splitclients[id].getTreatment("test")`

Anything I should have done differently?

**Comment by NicoZelaya** [comment]
Your safest bet would be to use the settings object from the factory directly. You could expose the features from the factory settings, e.g: 
`window.splitMockData = splitFactory.settings.features`.

Then you modify that one, for example:
`window.splitMockData.yourFeature = 'desired treatment'`

wait for the refresh rate to process that (you could enable logging if you want to see it) and call getTreatment/s again.

Hope it makes sense for you! I'll add something to our backlog to improve those docs and add a code  example that covers for the updates.

**Comment by jasonkim** [comment]
Ok, yeah, that makes way more sense. I'll try it out and let you know.
I'll close this for now and will reopen it if I encounter an issue with this again.
Thanks.
