### ISSUE TITLE
Incorrect ES6 import syntax causing warnings and missing data

### ISSUE THREAD

**Issue by kellym** [splitio/javascript-client#265]
This file is defined/imported elsewhere incorrectly: 
https://github.com/splitio/javascript-client/blob/development/src/utils/labels/index.js

It causes issues for at least the following lines.
https://github.com/splitio/javascript-client/blob/development/src/client/client.js#L11
https://github.com/splitio/javascript-client/blob/development/src/utils/inputValidation/split.js#L2

The files with issues are trying to use destructuring assignment on an import statement, but that's not a valid syntax. Brackets are only to be used for named exports.

**Comment by NicoZelaya** [comment]
Hey @kellym ! 

Sorry it took me a long time to get back to you, but version 10.7.2 was released already including your fix! Again, thank you so much for your contribution, really appreciated :)

Closing the issue for now but feel free to reach out if you experience any other hiccups. 

Best,
Nico.

**Comment by kellym** [comment]
No problem, thanks for the quick update!
