### ISSUE TITLE
Runtime failure with React Native

### ISSUE THREAD

**Issue by jdmunro** [splitio/javascript-client#280]
Using the latest package version (10.8.1) I get the following runtime error from split:

![Simulator Screen Shot - iPhone X - 2019-07-11 at 10 34 30](https://user-images.githubusercontent.com/17656/61041716-b82a1e00-a3ca-11e9-97f9-0662c9a1bf8f.png)

It seems to be related to the regenerator runtime. This is with React Native 0.59.x.

**Comment by NicoZelaya** [comment]
Hi @jdmunro !

We followed up with this via our Support channel, but version 10.8.2 is exposing the `/src` folder so you can keep the current approach to avoid the regenerator conflict.

Thank you very much for your patience! Don't hesitate reaching out if you have any other problems.

Best regards,
Nico.
