### ISSUE TITLE
TypeScript types for MockedFeaturesMap is out of date

### ISSUE THREAD

**Issue by thienmint** [splitio/javascript-client#284]
Referencing the code in this section: https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#localhost-mode

```
...
features: {
    'reporting_v2': 'on', // example with just a string value for the treatment
    'billing_updates': { treatment: 'visa', config: '{ 'color': 'blue'}' } //example of of a defined config 
    'show_status_bar': { treatment: 'off', config: null } // example of a null config
  },
...
```

There are 2 issues:
1. The example above is not valid (the quotes around `color` and `blue` should be `""`)
2. The types file doesn't reflect that you can do this.

Current:
```
type MockedFeaturesMap = {
    [featureName: string]: string
};
```

Should be:
```
type MockedFeaturesMap = {
    [featureName: string]: string | TreatmentWithConfig
};
```

I'm currently having to put a `ts-ignore` on every mocked split with config to mimic what would return by split working locally. Can we make an update and update the documentation for a valid example?

**Comment by patricioe** [comment]
Hey,

Our apologies for this inconsistency. We'll take a look shortly.

**Comment by patricioe** [comment]
We went ahead and update the docs.

As per the TS types, you can track the fix here: https://github.com/splitio/javascript-client/pull/285

**Comment by NicoZelaya** [comment]
Hi @thienmint,

we've released version 10.8.2 of our SDKs including this update for the typings file. If you can give it a try and let us know how it goes we'll appreciate it! 

I'll keep the issue open for a few days until we can confirm it's resolved. Thank you again for reaching out!

Best,
Nico.

**Comment by thienmint** [comment]
@NicoZelaya It works great. Thanks!

**Comment by NicoZelaya** [comment]
Thank you very much for the update!
