### ISSUE TITLE
react-native runtime error on newer versions than 10.15.1. missing 'events'

### ISSUE THREAD

**Issue by jeffreyffs** [splitio/javascript-client#296]
After upgrading to react-native 0.60.5, we also tried to update this package and are now receiving runtime errors that 'events' can't be found. Upgrading from 10.15.1 -> 10.8.2

It looks like this PR removed the dependency on `events` (https://github.com/splitio/javascript-client/commit/9d243360a2f29b0fe8ef93cc57d6de5438aaa438#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

but `readiness.js` is still importing it here: https://github.com/splitio/javascript-client/blob/development/src/readiness/index.js

![Screen Shot 2019-08-30 at 1 31 42 PM](https://user-images.githubusercontent.com/1441462/64050165-0e465280-cb2c-11e9-866d-f8f2d00d6906.png)

**Comment by NicoZelaya** [comment]
Hi @jeffreyffs !

I'm sorry to hear that. Yes, we removed the dependency in favor of the Node implementation but caused issues on RN, so we're adding it back as an optional dependency on the next versions.
There's also another one that falls under the same case, `utils`.

Can you try installing those two with npm or yarn?
`npm install --save events`
`npm install --save utils`

This should allow you to move forward for now, after next release you won't need to define it on your end.

Kind regards,
Nico.

**Comment by jeffreyffs** [comment]
Thank you for the quick response. I added `events` and `util` (not `utils` :) ) and everything is running again.

I look forward to the next release. Thanks again!

**Comment by NicoZelaya** [comment]
Oops! Sorry for the typo! 

Thank you for the quick update, I'll close the ticket but if you have any other issues feel free to create a new one.

Have a wonderful weekend!
