### ISSUE TITLE
Support for React Native?

### ISSUE THREAD

**Issue by ethanneff** [splitio/javascript-client#300]
I am getting the following error when trying to import Split.io into our React Native project:

```js
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `util` from `/Users/ethanneff//active/work/phoenix/node_modules/@splitsoftware/splitio/lib/utils/logger/LoggerFactory.js`: Module `util` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/ethanneff//active/work/phoenix/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/Users/ethanneff//active/work/phoenix/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/ethanneff//active/work/phoenix/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/ethanneff//active/work/phoenix/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/ethanneff//active/work/phoenix/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/ethanneff//active/work/phoenix/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/ethanneff//active/work/phoenix/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ethanneff//active/work/phoenix/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

The suggested instructions to fix did not solve the issue. Has anyone else used Split.io with a React Native project?

**Comment by NicoZelaya** [comment]
Hi @ethanneff !

Sorry for the inconveniences. Depending on how you're running, you might need to download two libraries from npm:
`npm i -S events utils`

The next release of the SDK will include this two listed as optional dependencies (as well as a few other dependency updates) so after that point you won't need to specify those anymore on your own package.json file.

Let us know if you're still experiencing some issues after installing those and we'll take a deeper look.

Regards,
Nico.

**Comment by chillaq** [comment]
Hi, we also have react native examples in our KB, links below:

https://help.split.io/hc/en-us/articles/360030904092-React-Native-iOS-App-using-Split-SDK-example
https://help.split.io/hc/en-us/articles/360030901212-React-Native-Android-App-using-Split-SDK-example

Thanks
Bilal

**Comment by chillaq** [comment]
Also, another example here: https://github.com/splitio/react-native-sdk-example

**Comment by jeffreyffs** [comment]
@NicoZelaya Is this resolved in 10.8.3? or another release after this one? Thanks!

**Comment by NicoZelaya** [comment]
It's going to be part of the next one, I'll can let you know here once it's done.

But if this is blocking you somehow please let me know and we'll figure out how to unblock you sooner rather than later. 
We're also trying to revamp our React Native example app and keeping an eye for other gaps while we do it. If we find something it'll most likely be fixed as part of the next release too.

Again, our sincere apologies for the inconveniences.
Best,
Nico.

**Comment by jeffreyffs** [comment]
The workaround (installing `util` and `events`) works for now. I'd just like to get rid of the extra lines in our package.json when possible. No rush. Thanks!

**Comment by ethanneff** [comment]
> Sorry for the inconveniences. Depending on how you're running, you might need to download two libraries from npm. Please run the following command:
> `npm i -S events util`

This solved my issue.

**Comment by jeffreyffs** [comment]
The latest version (10.8.4) works without adding `events` or `utils`. Thanks @NicoZelaya!

**Comment by NicoZelaya** [comment]
Glad to hear about that @jeffreyffs ! @ethanneff you should also be good to remove those dependencies after upgrading to version **10.8.4**

I'll go ahead and close the issue, but feel free to reopen or create a new one if you are still seeing this issue.

Best,
Nico.
