### ISSUE TITLE
Support for Nodejs 12

### ISSUE THREAD

**Issue by akankshagaur** [splitio/javascript-client#314]
Hi, 
I tried running the package with node 12 in my front end application & it gave build errors. 

Please provide support. 

Thanks
Akanksha Gaur

**Comment by NicoZelaya** [comment]
Hi @akankshagaur ! We've updated our Node typings on the latest release, 10.9.0.

Could you check if your issue is already resolved? I'll keep this issue open for a few days until we hear back from you.

**Comment by NicoZelaya** [comment]
Closing the issue for now, but feel free to reopen if you're still experiencing any problems with your build @akankshagaur !
