### ISSUE TITLE
Socket hang up

### ISSUE THREAD

**Issue by maximgeerinck** [splitio/javascript-client#349]
Having integrated Split.IO in our NestJS backend application we experience a lot of "Socket hang up" errors that are going to `https://events.split.io/api/metrics/times`.

We call the `destroy` function on module destroy. 

SplitIO version: 10.8.4

Our functions looks something like:

```
onModuleInit(): void {
    const factory = SplitFactory({
      core: {
        authorizationKey:
          this.configService.get('SPLIT_IO_API_KEY') || 'localhost',
      },
      startup: {
        readyTimeout: 30,
      },
    });
    this.client = factory.client();
    this.client.once(this.client.Event.SDK_READY, () => {
      this.isClientReady = true;
    });
  }
  onModuleDestroy(): void {
    this.client.destroy();
    this.client = null;
  }
```

after which we call a method to see if the split exists, ex:

```
  isSomeSplitActive = async (userId: number): Promise<number> =>
    Promise.resolve(
      (await this.client.getTreatment(String(userId),'some-split') === 'on')
        ? 1
        : 999,
    );
```

**Comment by NicoZelaya** [comment]
Hi @maximgeerinck ! 

thank you for reaching out and our apologies for the inconveniences this may have caused. 

While we try to repro, could you try using a promise to wait until the client flushed important data and stops synchronization before? I understand that you should be able to return a promise in `onModuleDestroy`.
```
async onModuleDestroy(): Promise<void> {
    const cleanRef = () => { this.client = null };

    return this.client.destroy().then(cleanRef).catch(cleanRef);
  }
```

If that doesn't solve the issue, could you share more details on how your app works? 
For example, is that module creating the SDK instantiated only once and being destroyed when the app closes? Or is it a module you instantiate multiple times? 

Thanks in advance,
Nico.

**Comment by maximgeerinck** [comment]
Hey, thank you for replying.
Your suggested change didn't work.

In NestJs this feature flag service is injected as a singleton. the onmoduledestroy is defined as "Cleanup just before Nest destroys the host module" (by nestjs).

**Comment by NicoZelaya** [comment]
Sorry to hear that @maximgeerinck.

We'll try to repro on our end, is there anything in particular we should take into account for our Nest setup?

**Comment by maximgeerinck** [comment]
Not really, it could be an app with a main module and a separate module where the feature flag service is located. the service would have a lifecycle like my original post. (https://docs.nestjs.com/fundamentals/lifecycle-events)

**Comment by NicoZelaya** [comment]
Cool! I'll talk with our support team to replicate that setup and will get back to you with our findings.

Nico.

**Comment by NicoZelaya** [comment]
Hi @maximgeerinck,

we had no luck trying to reproduce yet, one of our support engineers is looking at it. Could you elaborate a bit more about how and why is your app being closed? So he can try to replicate that scenario on his test setup.

**Comment by chillaq** [comment]
Hi @maximgeerinck,

I am following up on this issue, do you still require any assistance?

Thanks
Bilal

**Comment by maximgeerinck** [comment]
> Hi @maximgeerinck,
> 
> I am following up on this issue, do you still require any assistance?
> 
> Thanks
> Bilal

Hello, sorry for the late response. We don't require assistance anymore.

Thanks
