### ISSUE TITLE
Update axios version to 0.19.2

### ISSUE THREAD

**Issue by nadios** [splitio/javascript-client#350]
Could you please update the `axios` dependency to the latest version (`0.19.2`) as version `0.19.1` has some issues (https://github.com/axios/axios/pull/2679, https://github.com/axios/axios/issues/2646) which we experience.

**Comment by jpetersen-cuda** [comment]
+ 1

**Comment by NicoZelaya** [comment]
Hi @nadios,  thank you for flagging!

We'll definitely take care of this on our upcoming release, will let you know here once it's out.

Best,
Nico.
