### ISSUE TITLE
Split.io returns 404 if client key contains forwardslash or backslash

### ISSUE THREAD

**Issue by elliotleelewis** [splitio/javascript-client#364]
If your `core.key` value in the configuration in the SplitFactory contains a forwardslash or backslash, the API returns a 404. Ideally the key should be URL encoded before being sent to avoid this.

![image](https://user-images.githubusercontent.com/17044667/75278292-9ce41580-57d7-11ea-8fc4-f636b1ae0335.png)

In this scenario, my key is set to `test/key`. The same behaviour occurs when the key is `test\key`.

**Comment by chillaq** [comment]
Hi Elliot, this is a known issue, we are working on a fix, will let you know once I have ETA.

Thanks
Bilal

**Comment by elliotleelewis** [comment]
Great, thank you!

**Comment by chillaq** [comment]
Hi Elliot, could you provide the usage case on using slashes in key ids? usually customers generate a hash key representing their users without the need for slashes.

Thanks
Bilal

**Comment by elliotleelewis** [comment]
So we like being able to track our user logins in the split.io dashboard (therefore we dont hash), and the vast majority of our user logins have backslashes in them.

For me it also just doesn't make sense to append the key at the end of the URL. Why not use a query param or something, or even better URL Encode the key before appending it, just so that you can put whichever special characters in that you want, without fear that it will return a 404. 😄

**Comment by chillaq** [comment]
Hi Elliot, thanks for the Info, our Product manager would like to get on a call with you to understand the business case better, are you willing to participate in a zoom meeting?

Thanks
Bilal

**Comment by elliotleelewis** [comment]
Hi Bilal, sure. DM me on twitter, `@elliotleelewis`, and we can sort something out.

**Comment by chillaq** [comment]
Thanks Elliot, you can send me an email to bilal@split.io, I will send you the meeting invite.

**Comment by chillaq** [comment]
Hi Elliot, just want to let you know, we will be supporting the slashes in user ids, this means we will work on fixing all the issues in SDK and UI that resulted from having slashes. This is an on-going project, we will be pushing fixes gradually, please keep checking the CHANGES.txt file in each repo when a new version is released.

Let me know if you have any questions.

Thanks
Bilal

**Comment by elliotleelewis** [comment]
Thank you, I'll keep a lookout!
