### ISSUE TITLE
Multiple localhost split files

### ISSUE THREAD

**Issue by alexpusch** [splitio/javascript-client#387]
The localhost mode split file is a very useful feature. However it brings up a dilemma - do I commit the .split file or gitignore it? if I commit it, other team members will be force to take my preferred settings. If I .gitignore it, other users will have to construct the entire file from scratch.

A possible solution for that is to add the ability to have multiple split files. For example .split.defaults (commited) and .split (ignored)

**Comment by chillaq** [comment]
Hi Alex, we also support yaml files for localhost mode, you can store multiple yaml files in your repo.

Thanks
Bilal

**Comment by alexpusch** [comment]
Hi Bilal, thanks for the answer, but is there a way to configure more than one yaml files? according to the docs the way to configure a yaml file is to use this config - `  features: path.join(__dirname, '.split')`. seems that you only support a single file

**Comment by chillaq** [comment]
Hi Alex, you can initialize the split factory and point to one specific yaml file, update the  parameter configFilePath to point to the file path+name.

Thanks
Bilal

**Comment by alexpusch** [comment]
but what about multiple yaml settings file? I see it's not possible under the current API. Do you think it's a feature you might add?

**Comment by chillaq** [comment]
Hi Alex, the localhost mode usually used for unit testing, you can iterate through multiple yaml files initializing the factory with one yaml file in each iteration.

**Comment by alexpusch** [comment]
As I understand it, another use of the localhost file is for local running of the system, not just unitests. For this use case it would be useful to have multiple split files configured at once.

 For example .split.defaults (commited) would hold our default values for splits
 and .split (git ignored) which would be used by each individual team member to set their own values

**Comment by chillaq** [comment]
Hi Alex, Understood, I guess it is possible to use localhost mode for development, keep in mind the localhost mode support only treatments and whitelisted keys, there are lot of other features that Split UI supports like Targeting rules and default rule that does not exist in localhost mode.

**Comment by JonShort** [comment]
I've been handling this by including a `.split.example` file, which contans valid syntax; then when new developers join they can copy + paste it into a gitignored `.split` file (similar process to a `.env` file)

Works well for us because you can show developers what splits are available to them without actually changing the treatments returned to them when developing.

**Comment by chillaq** [comment]
Great, thanks.
