### ISSUE TITLE
How to get white-list information for given split

### ISSUE THREAD

**Issue by saiumesh-apty** [splitio/javascript-client#389]
How to get white-list users list for given split name. Thanks!

![image](https://user-images.githubusercontent.com/35692863/78884554-bc2dbe00-7a78-11ea-9c7b-22920d9394ee.png)

**Comment by chillaq** [comment]
Hi Salumesh, you can use Split Admin REST API to fetch Split definition information which include the whitelist section, checkout this link: https://docs.split.io/reference#get-split-definition-in-environment

You can also check the examples in this link: https://help.split.io/hc/en-us/sections/360004020552-Admin-API-Examples

Thanks
Bilal

**Comment by saiumesh-apty** [comment]
@chillaq Thanks for the response. Is any way to get whitelist information from SDK?
The requirement is, we have multiple tenants and we would like to show some features to specific users only. I've added users to the whitelist section and would like to retrieve that information.
Thanks!

**Comment by chillaq** [comment]
Hi Salumesh, currently within SDK we don't have a way of retrieving the whilelist section. If I understand you correctly, you can serve the feature to only whitelisted users if their ids are in the "on" treatment whitelist section, and set the default rule to "off".
This way, getTreatment call will only return "on" for the whitelisted users.

Thanks
Bilal

**Comment by saiumesh-apty** [comment]
@chillaq Thanks for the help.
