### ISSUE TITLE
require ioredis crashes when no optional dependencies installed

### ISSUE THREAD

**Issue by MichaelKohler** [splitio/javascript-client#400]
[RedisAdapter](https://github.com/splitio/javascript-client/blob/3ee5d2b58007ed623f35ba0ae78fd492b6b7f05d/src/storage/RedisAdapter.js) is using `ioredis`. And RedisAdapter is required from [storage/node.js](https://github.com/splitio/javascript-client/blob/e1002a31464fb155079f74d3200af81fa0ba1221/src/storage/node.js). However, ioredis is tagged as optional dependency here: https://github.com/splitio/javascript-client/blob/a9108c2f4e69fc5ff03426cbe03dbcf6f3dcfd28/package.json#L46

As ioredis is required without any check, this leads to a crash when optional dependencies are not installed.

I haven't checked the events package, but that might be the same issue.

**Comment by neophob** [comment]
any comments/hints about this issue? does someone care? do you accept PR's?

**Comment by chillaq** [comment]
Hi Guys, Sorry about the delay, the reason we set ioredis as optional so that it will not be bundled to the Javascript lib when the SDK runs on the browser, since Redis is not supported on browser mode, only server mode. This is done to reduce the size of browser lib.

Thanks
Bilal

**Comment by MichaelKohler** [comment]
I'm not saying anything against optional dependencies. But when you mark a dependency as optional, you should add a check if it's installed before requiring it so it doesn't crash. Can you have a look at that? Thanks!

**Comment by chillaq** [comment]
Thanks Michael, that makes sense.

**Comment by chillaq** [comment]
Hi Michael, issue is fixed in version 10.12.2, ioredis now is required dependency.

**Comment by chillaq** [comment]
Hi Michael, version 10.12.2 is not released yet, will let you know once it is out, sorry about that.

**Comment by chillaq** [comment]
Hi Michael, the fix is released in 10.13.0
