### ISSUE TITLE
/node_modules/@splitsoftware/splitio/types"' has no exported member 'SplitIO'.

### ISSUE THREAD

**Issue by crh225** [splitio/javascript-client#451]
I am trying to import the splitIo namespace and am getting the following errors
![image](https://user-images.githubusercontent.com/19475195/87701166-2089a900-c75d-11ea-838c-1491036b71de.png)

**Comment by chillaq** [comment]
Hi, you need to import SplitFactory only, no need to import SplitIO, see example below:

import { SplitFactory } from '@splitsoftware/splitio';
const factory: SplitIO.ISDK = SplitFactory({ 
  core: {
    authorizationKey: 'YOUR_API_KEY'
  }
});
const client: SplitIO.IClient = factory.client();

**Comment by crh225** [comment]
my issue is with the angular demo yall have. I took that code and stuck it in my custom angular library. Im on angular 10, and the split.io code is wrapped in a angular module inside a library. when using my lib inside another angular app, it is throwing those errors

**Comment by chillaq** [comment]
Hi Chris, did you use this link: https://github.com/splitio/angular-sdk-examples?

I don't see any "import {SplitIO} from .... " in the repo.

**Comment by NicoZelaya** [comment]
Our typings file is referenced via the `types` field of our package.json. How is your app loading these when resolving the types? do you know? 
It's an exported namespace, are you defining a namespace called SplitIO anywhere? If you go to the node_modules folder, is the /types subfolder there with two files?

**Comment by crh225** [comment]
Yall have to be the fastest people answering questions on github, so thanks!

@chillaq I understand they dont have that in the repo anywhere. I only added it as an example, and to say that that exported namespace wasnt working for me. I tried it not in a library and it works.

@NicoZelaya I tried just like in the angular example.
I only added this to my tsconfig
```    "typeRoots": [
      "node_modules/@types"
    ]
```
To clarify, I added it to the library's tsconfig only.

**Comment by crh225** [comment]
I also upgraded the angular demo app to latest: https://github.com/splitio/angular-sdk-examples/pull/9

**Comment by chillaq** [comment]
Hi @crh225, I have an update:
TypeScript implicitly imports SplitIO namespace when doing import { SplitFactory } from '@splitsoftware/splitio'; , and even the “typeRoots” config is not affecting it because the declaration file is included in the sdk package and the “types” field is properly configured.

You can explicitly import the SplitIO namespace (for example, on modules/files where SplitFactory is not being imported), the way to do it is: 
import SplitIO from '@splitsoftware/splitio/types/splitio'; // requires `"allowSyntheticDefaultImports": true` in tsconfig

**Comment by chillaq** [comment]
Hi @crh225, closing this issue for now, please let me know if you need any further assistance.

Thanks
Bilal
