### ISSUE TITLE
getTreatment: attributes must be a plain object.

### ISSUE THREAD

**Issue by kumaresanm** [splitio/javascript-client#453]
I am using the JS sdk.
    const attributes = {};
    const treatment = this.client.getTreatment('default', 'split1', attributes);
    console.log(treatment);
when i do this i am getting the error: getTreatment: attributes must be a plain object.

![image](https://user-images.githubusercontent.com/5888338/88392526-c3839800-cdd9-11ea-8f8c-71719fe5ac74.png)

**Comment by chillaq** [comment]
Hi Kumaresan, using Javascript on browser, the getTreatment() method takes only 2 parameters: split name and attributes, the user id is defined in the factory core info:
const attributes = {};
const treatment = this.client.getTreatment('split1', attributes);

**Comment by chillaq** [comment]
Hi Kumaresan, I am closing this issue, please let us know if you need more help.

Thanks
Bilal
