### ISSUE TITLE
Cannot read property 'matchers' of undefined / Version 10.14.0

### ISSUE THREAD

**Issue by esbanarango** [splitio/javascript-client#462]
I'm using version `10.14.0` and I'm getting this error when calling: `client.getTreatment('split-name')`

`index.js:39 Uncaught (in promise) TypeError: Cannot read property 'matchers' of undefined`

<img width="854" alt="Image 2020-08-05 at 6 08 37 PM" src="https://user-images.githubusercontent.com/1156865/89472727-b4d8a180-d746-11ea-9051-3af4596f5e5c.png">

**NOTE:** This works fine on version 10.13.0

**Comment by chillaq** [comment]
Hi Esteban, thanks for the info, could you please provide the config parameters used for the SDK? Also first 4 characters of the API Key.

Thanks
Bilal

**Comment by esbanarango** [comment]
The API Key I'm using is `localhost` as I was testing this initially on development.
```js
    let factory = SplitFactory({
      core: {
        authorizationKey: config.splitioApiKey,
        key: companyId,
        trafficType: this.trafficType
      },
      storage: {
        type: 'LOCALSTORAGE'
      },
      startup: {
        requestTimeoutBeforeReady: 9.1, // 9100 ms
        retriesOnFailureBeforeReady: 3, // 3 times
        readyTimeout: 9.1 // 9100 ms
      },
      // these features are only picked up for 'offline' split.io clients
      // which is the default in development and test
      features: config.features
    });
```

**Comment by chillaq** [comment]
Hi Esteban, the code looks good, what is the config.features content?

Thanks
Bilal

**Comment by esbanarango** [comment]
It's just an object to control feature flags on DEV:

```js
features: {
  'touchless-walk-in-language-support': process.env.FEATURE_LANGUAGE_SUPPORT || 'on'
}
```

**Comment by chillaq** [comment]
Hi Esteban, We cannot repro this issue.
Could you provide more details of the tools used to build the project?
for example, the webpack version, if create-react-app tool is used or some other bundler/transpiler/parser, etc and what versions.
also the browser version on the screenshot. and some log messages from the console could also help.

**Comment by esbanarango** [comment]
Hey @chillaq, I'm using ember.js with `"ember-cli": "~3.20.0"` and `"node": "12.18.2"`. `@babel/core 7.11.1` is also used internally by ember-cli. I had this issue with both Fireforx (😍) and Chrome (🥴). Again this is working fine with the previous version `10.13.0`.

**Comment by chillaq** [comment]
Hi Esteban,  we found the reason of the issue and we will be releasing a fix next week.
in the meantime, also share with them the release candidate to try temporally.
it can be simply installed with a npm install @splitsoftware/splitio@10.14.1-canary.1

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Esteban, we released JS SDK v10.14.1 that fixes this issue.

Thanks
Bilal

**Comment by esbanarango** [comment]
Thank you, I'll test that version next week 🙏

**Comment by NicoZelaya** [comment]
Hi @esbanarango! 

Sorry for the ping, wanted to confirm if you had a chance to try it? Should we revisit or good to close?

**Comment by esbanarango** [comment]
👍 We're good now
