### ISSUE TITLE
[Bug] Set is Not Defined on Android 4.4

### ISSUE THREAD

**Issue by jefrydco** [splitio/javascript-client#488]
Hi, we try to integrate Split JavaScript SDK to our app that support Android till version 4.4. But when we open our app on Android 4.4, it becomes a whitescreen. After investigating, it turns out that the cause is Set Ponyfill.

https://github.com/splitio/javascript-client/blob/1d340afa17bc4b41f92757fd6b54539c87f3b7fe/src/utils/lang/Sets.js#L88

The following image is screencapture of remote debugging devtool on Android 4.4:

![Set is not defined Split on Android 4.4](https://user-images.githubusercontent.com/20434351/93485857-ba243100-f92d-11ea-8322-5dd1d66885ee.png)

Checking `!Set.prototype.values` will throw error because `Set` itself is undefined on Android 4.4. I think we should refactor it to something like this `!window.Set || !(window.Set && window.Set.prototype.values)`.

After changing that line directly on `node_modules` dir, it solve the problem

![Solution Set is not defined Split on Android 4.4](https://user-images.githubusercontent.com/20434351/93486232-26069980-f92e-11ea-9a19-9f4b415758ea.png)

**Comment by NicoZelaya** [comment]
Hi @jefrydco ! Thanks for reporting this. We'll take it, probably starting from your PR and issue a fix shortly. 

One thing we can't do is tie ourselves to the `window` object, given not all our targets are Browser~like and have a window global.
On that note, our developer wants to understand if you're opening a web page on an Android device with Android 4.4 and in that case, which browser and browser version. In case it's an Android app running on a webview or webview based framework like Ionic, could you provide more data about your stack and the environment where you get the failure? 

We'll keep you posted on the work we do. Thank you again for the report.

Have a wonderful day,
Nico.

**Comment by jefrydco** [comment]
Ah I see, at first I think name `javascript-client`, that `client` part is running on the browser. So it should be probably fix the issue, but it turns out that this SDK is also run on other environment.

The app is running on a webview and we have our own webview wrapper that seems wrap around the original Android webview. That is a native Android webview not webview based framework. And the thing is, although we open it outside our app's webview and as long as in Android 4.4 native browser, it still raise an error like I mention above.

How we reproduce that issue:
1. Run a webapp that use Split SDK in a production build.
2. Open in a native browser/webview on Android 4.4.
3. It should raise an error like I share above and make the app white screen.

**Comment by NicoZelaya** [comment]
The repo is called this way due to the language target, but it can be executed on any JS environment, as long as there's a JavaScript engine underneath.

Thanks for confirming! We could repro on our end too and testing a fix, luckily we went through the Android 4.4 native browser route.

Will keep you posted as it goes through our pipeline and we prepare for a release.

**Comment by jefrydco** [comment]
Thank you! Any eta when we can get the fix?

**Comment by NicoZelaya** [comment]
We're aiming for today EOD! It'll be a patch version.

**Comment by EmilianoSanchez** [comment]
hi @jefrydco. 
We have released a new patch version of the JS SDK ([v10.14.2](https://www.npmjs.com/package/@splitsoftware/splitio/v/10.14.2)) that includes a fix for your issue.

Have a good day, 
Emiliano

**Comment by jefrydco** [comment]
Thank you! Will try that version and let me update you whether the problem still exist or not on ourside then I'll close this issue and the PR as well
