### ISSUE TITLE
Maximum Call Stack Size Exceeded

### ISSUE THREAD

**Issue by jefrydco** [splitio/javascript-client#500]
Hi, we recently we got hundreds of error that make our app whitescreen. The error message is "Maximum call stack exceeded". After some investigation, it seems the error thrown from this SDK somewhere around this line:

![jefrydco - split.io](https://user-images.githubusercontent.com/20434351/99049662-b0cfe180-25c9-11eb-9547-e2ae0e360c74.png)

More information about the environment:
We implement this SDK in webview application
JavaScript SDK Version: 10.14.2
OS where the error happens: Android

cc: @akbarnafisa

**Comment by chillaq** [comment]
Hi Jefry, Could you provide the code that use the SDK? One thing to check is to use a singleton for Split factory object, and not create new factory everytime getTreatment is called.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @jefrydco, I am following up on this issue, do you still require any assistance?

**Comment by jefrydco** [comment]
Hi @chillaq sorry for very late response, recently we change our implementation. We're waiting for it to be deployed to production to see whether it already fixed this issue or not. I'll close this issue for now and reopen it if its still persist. Thank you!
