### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ying80** [splitio/javascript-client#503]
Currently, I am running a heavily visited expressjs app and the splitIO client has introduced a memory leak. 
I keep a MySplitIO object around and keep calling mySplitio.getTreatment() for each request.
Should I be making a new splitio client for each request and call destroy() after each request? I am using version 10.12.1. 
Thanks!

```
class MySplitIO {
  constructor() {
    const client = SplitFactory(..).client();
  }

  async getTreatment(...) {
    await client.ready();
    await client. getTreatmentsWithConfig(...);   // <--- memory leak
  }
}
```

**Comment by chillaq** [comment]
Hi @ying80, your code looks ok, no need to create new client and destroy it as long as you use client as a singleton.

I will try to repro and get back to you.

Thanks
Bilal

**Comment by ying80** [comment]
Thanks @chillaq !

**Comment by chillaq** [comment]
Hi @ying80, are you running on browser or node side?

Thanks
Bilal

**Comment by ying80** [comment]
Node side

**Comment by chillaq** [comment]
Hi @ying80, I cannot repro. I do see the memory increase gradually as the impression records are added to the cache, after a minute, the post impressions thread kicks in and post the impressions and clears the cache, and memory usage goes down. Checkout the output.csv file, last column is the mem usage.

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function run() {
  var SplitFactory = require('@splitsoftware/splitio').SplitFactory;
  var SplitObj = SplitFactory({
    core: {
          authorizationKey: 'xxxxxx'
    },
  });
  var client = SplitObj.client();
  client.ready().then( async () => {
        console.log("SDK is ready");
        console.log("Time, treatment, config, memory Usage");
        for (var i=1; i<1000; i++) {
	        var splitResult = client.getTreatmentsWithConfig(i.toString(), ["sample_feature"]);
	        const used = process.memoryUsage().heapUsed / 1024 / 1024;
	        var memUsed = Math.round(used * 100) / 100;
	        console.log(Date().toString()+","+splitResult.sample_feature.treatment+","+splitResult.sample_feature.config+","+memUsed.toString());
	        await sleep(1000);
        }
    });
};

run();


[output.csv.zip](https://github.com/splitio/javascript-client/files/5663630/output.csv.zip)

**Comment by ying80** [comment]
@chillaq thank you so much for looking into this! I think the issue might be related to our k8s pods are too small. They have a mem limit of 512Mi. I am going to test with 1.5Gi...I will let you know if it helps. Thanks!

**Comment by ying80** [comment]
After testing with 1.5Gi, the memory issue is gone. :)
