### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'o.map')

### ISSUE THREAD

**Issue by oaosman84** [splitio/javascript-client#508]
In our ReactNative app on version 10.10.0 of the splitio client, we're seeing app crashes with the following error:

```
TypeError: undefined is not an object (evaluating 'o.map')
  at default(/Users/runner/work/1/s/packages/common/node_modules/core-js-pure/es/instance/map.js:6:13)
  at handler(/Users/runner/work/1/s/packages/common/node_modules/@splitsoftware/splitio/lib/producer/fetcher/MySegments.js:56:21)
  at fn(/Users/runner/work/1/s/packages/common/node_modules/core-js-pure/modules/es.promise.js:114:22)
  at fn(/Users/runner/work/1/s/packages/common/node_modules/core-js-pure/internals/microtask.js:26:9)
  at tryCallOne(node_modules/react-native/node_modules/promise/setimmediate/core.js:37:12)
  at callback(node_modules/react-native/node_modules/promise/setimmediate/core.js:123:15)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:7)
  at _callImmediatesPass(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:5)
  at _immediatesCallback(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:12)
  at __callImmediates(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:12)
  at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:9)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:10)
  at value(app:///[native code])
  at value(app:///[native code])
```

**Comment by chillaq** [comment]
Hi @oaosman84 , thanks for the info, any chance you can provide the code that uses the SDK?

**Comment by vanessa** [comment]
@chillaq This is the class we have that uses the SDK. Hope this helps!
```ts
class SplitClient {
  private factory: SplitIO.ISDK | undefined;
  private client: SplitIO.IClient | undefined;
  private onFlagsUpdated: (client: SplitIO.IClient, attrs: SplitAttrs) => void;
  private apiKey: string;
  private getNodeEnv: () => string;

  constructor(
    onFlagsUpdated: (client: SplitIO.IClient, attrs: SplitAttrs) => void,
    getNodeEnv: () => string,
    apiKey: string,
  ) {
    this.onFlagsUpdated = onFlagsUpdated;
    this.apiKey = apiKey;
    this.getNodeEnv = getNodeEnv;
  }

  init = (key: Id, attrs: SplitAttrs = {}) => {
    if (this.client) {
      // Init called twice before ready event has been fired
      this.client.removeAllListeners();
    }

    this.factory = SplitFactory({
      core: {
        authorizationKey: this.apiKey,
        key,
      },
      scheduler: {
        featuresRefreshRate: this.getNodeEnv() === 'development' ? 5 : 30, // seconds
      },
    });
    this.client = this.factory.client();
    this.client.once(this.client.Event.SDK_READY, () => {
      if (this.client) {
        this.onFlagsUpdated(this.client, attrs);
      }
    });
    this.setupUpdateListener(attrs);
  };

  setupUpdateListener = (attrs: SplitAttrs = {}) => {
    if (!this.client) {
      throw new Error('Client does not exist');
    }
    this.client.on(this.client.Event.SDK_UPDATE, () => {
      if (this.client) {
        this.onFlagsUpdated(this.client, attrs);
      }
    });
  };

  changeKey = (key: Id, attrs: SplitAttrs = {}) => {
    if (!this.client) {
      throw new Error('Client does not exist');
    }
    if (!this.factory) {
      throw new Error('Factory does not exist');
    }
    this.client.removeAllListeners();
    this.client = this.factory.client(key);
    this.setupUpdateListener(attrs);
    this.onFlagsUpdated(this.client, attrs);
  };

  destroy = () => {
    this.client?.removeAllListeners() && this.client?.destroy();
  };
}
```

**Comment by chillaq** [comment]
Thanks @oaosman84, the issue is coming from MySegment call, it usually return a JSON structure, I think the error occurs when the payload returns with empty string. This can happen if the key passed is null or empty string, since SDK append the key provided in factory to mysegment URL and it returns 404 if key is null.

Do you know if such scenario is possible with the app?

Thanks
Bilal

**Comment by vanessa** [comment]
@chillaq Hey, thanks for answering.

We don't use segments. Not sure this helps, but this issue is happening with users on iOS 14.3.

**Comment by chillaq** [comment]
Hi @vanessa, the SDK will call mySegment URL regardless if you use segments or not, the important part is you provide a valid value for the "key", as the value is appended to the URL that SDK is calling.
 
this.factory = SplitFactory({
      core: {
        authorizationKey: this.apiKey,
        key: 'key',
      },

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @vanessa , I am following up on this issue, do you still require any assistance?

Thanks
Bilal

**Comment by EmilianoSanchez** [comment]
Hi everyone, 
FYI, since version `10.14.0` of the  JS SDK, we have upgraded some dependencies and removed the `core-js` dependency that seems to be the one that is causing issues in your project. 
I would try upgrading the SDK version.

> In our ReactNative app on version 10.10.0 of the splitio client, we're seeing app crashes with the following error:
> 
> ```
> TypeError: undefined is not an object (evaluating 'o.map')
>   at default(/Users/runner/work/1/s/packages/common/node_modules/core-js-pure/es/instance/map.js:6:13)
>   at handler(/Users/runner/work/1/s/packages/common/node_modules/@splitsoftware/splitio/lib/producer/fetcher/MySegments.js:56:21)
>   at fn(/Users/runner/work/1/s/packages/common/node_modules/core-js-pure/modules/es.promise.js:114:22)
>   at fn(/Users/runner/work/1/s/packages/common/node_modules/core-js-pure/internals/microtask.js:26:9)
>   at tryCallOne(node_modules/react-native/node_modules/promise/setimmediate/core.js:37:12)
>   at callback(node_modules/react-native/node_modules/promise/setimmediate/core.js:123:15)
>   at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:7)
>   at _callImmediatesPass(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:5)
>   at _immediatesCallback(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:12)
>   at __callImmediates(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:12)
>   at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
>   at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:9)
>   at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:10)
>   at value(app:///[native code])
>   at value(app:///[native code])
> ```

**Comment by vanessa** [comment]
Hey @chillaq, the problem was related to a user using a DNS blocker. I think this can be closed.

@EmilianoSanchez Thanks for the heads up!

**Comment by chillaq** [comment]
Great, thanks
