### ISSUE TITLE
type SplitView should include tags

### ISSUE THREAD

**Issue by elbandito** [splitio/javascript-client#531]
Maybe this already exists, but I'm struggling to find ways to filter Split Views returned by `manager.splits()`.   It would be advantageous to have access to the same `tags` that are exposed via the web UI/dashboard to aid in filtering.   Any tips?

Looks like tags are being exposed via the API:
https://docs.split.io/reference#list-splits

**Comment by chillaq** [comment]
Hi @elbandito, The Manage object does not do a query against split cloud, instead is expose list of splits from the SDK cache, meaning the Splits that were downloaded to the SDK and are part of the environment that is associated with the used SDK API Key.
Split tags are not downloaded by the SDK.

The Admin REST API call in the URL referenced use different end point, its actually searching all splits on the backend that are created within the workspace, regardless of which environment they are added to.

Hope that helps.

Thanks
Bilal

**Comment by elbandito** [comment]
Thanks for clarifying, @chillaq.   So bottom-line, if I want the ability to filter off of `tags`, I would need to use the `Admin REST API`?

**Comment by chillaq** [comment]
That is correct. Keep in mind the Admin REST API does not provide calculating treatments functionality.
