### ISSUE TITLE
Anonymous functions cause warnings

### ISSUE THREAD

**Issue by Jakst** [splitio/javascript-client#535]
The anonymous functions in `src/utils/settings/runtime/node.js` and `src/utils/settings/runtime/browser.js` cause lots of warnings when transpiled.

Since we support IE11, we need to transpile `@splitsoftware/splitio-react` in our build process. When doing this, react starts throwing warnings about anonymous functions breaking the Fast Refresh feature. More specifically, it points out the two files mentioned above in this package.

I hope you can publish a new version of the react client with these functions named, so we don't get our console spammed with warnings 🙏

**Comment by NicoZelaya** [comment]
Hi @Jakst ! 

Apologies for the inconveniences and thanks for reporting! I'll try the change later but it looks like something we can probably squeeze into an upcoming patch that we're also carrying over to the React client. 
Will let you know ideally before EOD (but for sure before EOW) when you might be expecting the patch for the React SDK client.  

Thanks again!
Nico.

**Comment by Jakst** [comment]
Thanks for the quick response Nico! Looking forward to it.

**Comment by NicoZelaya** [comment]
Hi @Jakst !

I've included the changes in this PR (lazy me): https://github.com/splitio/javascript-client/pull/532 

Tested quickly and it seems good as I was expecting, we'll run it in staging for few days but next week if not before, the final release should be done and carried over to React SDK. 
I'll ping you here once it's finally out to close the loop!

**Comment by EmilianoSanchez** [comment]
Hi @Jakst , 

You can finally check the new version of the React SDK ([v1.2.6](https://www.npmjs.com/package/@splitsoftware/splitio-react/v/1.2.6)) with the update Nico mentioned.

Apologies for the delay but we wanted to add a few more vulnerability patches in this release together with other updates.

Thank you,
Emiliano

**Comment by Jakst** [comment]
Great, I will update immediately. Thanks for getting back to me!

**Comment by Jakst** [comment]
Following up on this, I noticed that this case of the problem was fixed, but that the issue exists in (at least) one more place in the code base, and so we are still getting warnings. The two functions located in `src/services/request/options` are the ones that popped up now instead.

Ping @NicoZelaya  @EmilianoSanchez
