### ISSUE TITLE
Split.io JS SDK uses `utfx` which is a CommonJS dependency, which throws warnings whenever used within an Angular project

### ISSUE THREAD

**Issue by elliotleelewis** [splitio/javascript-client#544]
Using CommonJS dependencies is against recommended best practices (see here https://web.dev/commonjs-larger-bundles/), and so Angular has started throwing warnings at compile time as they can cause increased bundle sizes. Can we remove the dependency on `utfx`? I've noticed that it's a library that's source code is archived, and the latest publish was 6 years ago, so it's probably something that should be removed anyway?

Here's an example of the warning that Angular throws:
```
Warning: C:\Projects\test-project\node_modules\@splitsoftware\splitio\es\engine\engine\murmur3\index.js depends on 'utfx'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by chillaq** [comment]
Hi @elliotleelewis , thanks for the info, will check with the team.

**Comment by EmilianoSanchez** [comment]
Hi @elliotleelewis

Please, checkout the new version of the JS SDK ([v10.15.7](https://www.npmjs.com/package/@splitsoftware/splitio/v/10.15.7)). It includes an update that should resolve your issue. Basically, we have removed the `utfx` dependency and use an internal module instead, which also helped us to reduce the code size.

Thanks,
Emiliano

**Comment by EmilianoSanchez** [comment]
I am closing this issue @elliotleelewis , but feel free to re-open it if the problem persists. 
Thank you

**Comment by elliotleelewis** [comment]
@EmilianoSanchez This works perfectly! Thanks for the quick turnaround on the change. 👍
