### ISSUE TITLE
localhost mode is never ready, always times out.

### ISSUE THREAD

**Issue by pauldraper** [splitio/javascript-client#556]
```js
const { SplitFactory } = require('@splitsoftware/splitio');

(async () => {
  const factory = SplitFactory({ core: { authorizationKey: 'localhost' }});

  const client = factory.client();

  console.log('start');

  await new Promise((resolve, reject) => {
    client.on(client.Event.SDK_READY, resolve);
    client.on(client.Event.SDK_READY_TIMED_OUT, e => reject(new Error(e)));
  });

  console.log('done');

  await client.destroy();
})().catch(e => {
  console.error(e.stack);
  process.exit(1);
});
```

```
start
Error: Split SDK emitted SDK_READY_TIMED_OUT event.
    at EventEmitter.<anonymous> (/home/paul/rivet/main6/api/test2.js:12:61)
    at EventEmitter.emit (events.js:215:7)
    at Timeout._onTimeout (/home/paul/rivet/main6/api/node_modules/@splitsoftware/splitio/lib/readiness/index.js:92:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

What I expected: The SDK_READY event to fire without delay.

What I got: The SDK_READY event does not fire. The SDK_READY_TIMED_OUT event fires after several seconds.

**Comment by chillaq** [comment]
Hi @pauldraper , when using "localhost", the SDK will look for the Split definitions from the "features" config parameter, I don't see it in your code, see example below:
var sdk = splitio({
  core: {
    authorizationKey: 'localhost'
  },
  features: {
   'reporting_v2': 'on', // example with just a string value for the treatment
   'billing_updates': { treatment: 'visa', config: '{ "color": "blue" }' }, //example of a defined config 
   'show_status_bar': { treatment: 'off', config: null } // example of a null config
 },
  scheduler: {
    offlineRefreshRate: 15 // 15 sec
  }
});

**Comment by pauldraper** [comment]
That doesn't make a difference to the issue though.

```js
const { SplitFactory } = require('@splitsoftware/splitio');

(async () => {
  const factory = SplitFactory({ core: { authorizationKey: 'localhost' }, features: { example: 'a' }});

  const client = factory.client();

  console.log('start');

  await new Promise((resolve, reject) => {
    client.on(client.Event.SDK_READY, resolve);
    client.on(client.Event.SDK_READY_TIMED_OUT, e => reject(new Error(e)));
  });

  console.log('done');

  await client.destroy();
})().catch(e => {
  console.error(e.stack);
  process.exit(1);
});
```

Same result.

**Comment by chillaq** [comment]
Hi @pauldraper , I tested the code below using node and it works fine, make sure to use the latest SDK version. If the code below still does not work, please share the debug log.

function run() {
  var SplitFactory = require('@splitsoftware/splitio').SplitFactory;
  var SplitObj = SplitFactory({
    core: {
          authorizationKey: 'localhost'
    },
    features: {
          'reporting_v2': 'on', 
   		  'billing_updates': { treatment: 'visa', config: '{ "color": "blue" }' }, 
          'show_status_bar': { treatment: 'off', config: null } 
    },
    startup: {
          readyTimeout :10
    },
    debug: true
  });
  var client = SplitObj.client();
  client.on(client.Event.SDK_READY, () => {
        console.log("SDK is ready");
        console.log(client.getTreatment("id", "reporting_v2"));
  });
};

run();

**Comment by pauldraper** [comment]
@chillaq thanks for the tip on the debug log.

I see

```
[ERROR] splitio-producer:offline => There was an issue loading the mock Splits data, no changes will be applied to the current cache. Error: Split configuration not found in /home/paul/.split - Please review your Split file location.
```

If I add that file `/home/paul/.split`, it then works as expected.

**Comment by chillaq** [comment]
Great, thanks.
