### ISSUE TITLE
Large bundle size

### ISSUE THREAD

**Issue by pauldraper** [splitio/javascript-client#559]
Bundled and minified, Split is 100KB.

That's pretty large for a library that just reads feature flags.

Any ideas for making that smaller?

![2021-07-14_09-17](https://user-images.githubusercontent.com/1403271/125647643-61713fe3-e593-4f7f-a8bb-7cb7aa2e080d.png)

**Comment by NicoZelaya** [comment]
Hi @pauldraper !

There are a few reasons for the size as it doesn't read flags from an external source, but covers bucketing without the need to ingest your customer data, different syncing options and enables experimentation use cases; all things that required some extra bytes. 
Nevertheless I see you are bundling for the browser, maybe you should check out our Browser SDK which is a little bit lighter and supports a pluggable interface. It doesn't offer 100% of the features from this repository yet but has the main API fully supported. 

Read more here:
- https://help.split.io/hc/en-us/articles/360058730852-Browser-SDK
- Maybe also check step 3 here https://www.split.io/blog/the-journey-to-improve-our-web-sdks/

Hope it helps!

**Comment by pauldraper** [comment]
> it doesn't read flags from an external source

Yeah, I know. But at the end of the day, that is the role it fulfills.

> check out our Browser SDK 

@NicoZelaya, I noticed that npm package while looking at this today. Thanks for those resources.

**Comment by rahulk94** [comment]
Hmm comparing the two on BundlePhobia doesn't show much difference in terms of overall size?
* https://bundlephobia.com/package/@splitsoftware/splitio-browserjs@0.3.0
* https://bundlephobia.com/package/@splitsoftware/splitio@10.17.1

@pauldraper did you notice any size reductions moving to the browser API?

@NicoZelaya are there any planned improvements to be able to shake some of this library if consumer's aren't using certain features?

**Comment by rahulk94** [comment]
Awesome @EmilianoSanchez! Thanks for the explanation, that really helps 🙂
