### ISSUE TITLE
TypeScript types for ISettings.features is incorrect

### ISSUE THREAD

**Issue by mabranon** [splitio/javascript-client#560]
In reference to https://github.com/splitio/javascript-client/blob/bcb196d4773fa612b9bbfc19c747fa711ade71d0/types/splitio.d.ts#L98-L100

It looks like the type here should be changed to one of the following:
```js
features: {
  [featureName: string]: string | TreatmentWithConfig
}
```

or 

```js
features: MockedFeaturesMap
```

**Comment by chillaq** [comment]
Hi @mabranon , thanks for the info, will check with the team.

**Comment by EmilianoSanchez** [comment]
Hi @mabranon ,

We have applied your suggestion in the last patch release of JS SDK (v.10.15.9).

Just to mention that the proper TypeScript type is now:
```
features: SplitIO.MockedFeaturesMap | SplitIO.MockedFeaturesFilePath,
```

It can be casted to `SplitIO.MockedFeaturesMap`, if using in Browser, or to `SplitIO.MockedFeaturesFilePath` if using in Node.

Thanks,
Emiliano
