### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by crenus** [splitio/javascript-client#617]
Hey is proxy configuration supported as part of the nodejs sdk? I dont see it in the docs, but I see it in the Java sdk docs

**Comment by chillaq** [comment]
Hi @crenus, Thanks for the info, you are correct, the Node environment does not pickup the network proxy environment variables like Java, so we have to add the proxy in the code and provide some parameters for it.

Some NodeJS libraries accept special proxy config parameters passed to node, but the network lib SDK uses does not unfortunately.

I will submit a feature request on your behalf.

Thanks
Bilal

**Comment by crenus** [comment]
Thanks! Do you happen to have any timeline on this?

**Comment by chillaq** [comment]
Hi @crenus, no ETA usually available for Feature Requests, as a workaround, the NodeJS SDK does support using the Split Synchronizer proxy app as a network proxy. The Synchronizer proxy app supports picking up the network proxy from environment variables.

Thanks
Bilal

**Comment by crenus** [comment]
Hi there,
So I have tried the above leveraging the proxy. The Proxy itself works, and I can see and validate that through the admin screen, as well as hitting localhost:3000 and passing keys.

From the sdk on the otherhand, when I pass the urls parameter, it doesnt work and getTreatments just responds with control. I am running the proxy in debug mode, and i also dont even see the requests getting there as I can see they do from Postman.

This is my factory:
const factory = SplitFactory({
	core: {
	  authorizationKey: 'dummy',
	},
	urls: {
	  streaming: 'http://localhost:3000/api',
	  sdk: 'http://localhost:3000/api',
	  events: 'http://localhost:3000/api',
	  auth: 'http://localhost:3000/api',
	},
});

then
const treatment = this.client.getTreatment('anonymous', split, { customerId, });

App is initialized, so client is done as starting up as well. 

If I remove the urls, and set the auth key properly to remote, it works locally.

**Comment by crenus** [comment]
Digging further when enabling debug, it is saying that http is not a supported protocol and it expects https. changing the endpoints to https, throws ssl errors, which to me is expected in this scenario because the proxy isnt setup using ssl and never would be.

**Comment by crenus** [comment]
I think the problem here is that when passing urls, it should support http. Not only that, but yours docs all have http included. An example like this is going to sit on a private network, im not going to set up certs and it doesnt look like Split Proxy supports that.

Are you saying in order for me to even make this solution work as well is that I have to set up a proxy in front of this proxy in order to forward requests just because this sdk does not support proxying or http?

**Comment by crenus** [comment]
Can we have this reopened? This is an issue. The other sdks work with the Split Proxy or leverage HTTP_PROXY/HTTPS_PROXY

**Comment by chillaq** [comment]
Hi @crenus , as of now, the NodeJS SDK only support the Split Proxy instance, I can check internally if we can enable http as well as https in the endpoints

Thanks
Bilal

**Comment by crenus** [comment]
Credit to @chrismangum

Posting solution for others to find. Can override the internal fetch call and inject our own agent.

Would you be able to add this to the docs? @chillaq 

`
const HttpsProxyAgent = require('https-proxy-agent');
const { SplitFactory } = require('@splitsoftware/splitio');
const { __setFetch } = require('@splitsoftware/splitio/lib/services/getFetch/node.js');

if (process.env.http_proxy) {
	const agent = new HttpsProxyAgent(process.env.http_proxy);
	__setFetch((url, options) => fetch(url, _.assign(options, { agent })));
}
`
