### ISSUE TITLE
Cannot read properties of undefined (reading 'response')

### ISSUE THREAD

**Issue by amakhrov** [splitio/javascript-client#621]
Thrown by the error handling code inside `.catch`: https://github.com/splitio/javascript-client/blob/development/src/services/transport/index.js#L22

I don't know the specific steps to reproduce, but it happens to a bunch of our users. In general, one cannot assume a caught error has any particular data type (or even is defined)

**Comment by EmilianoSanchez** [comment]
Thanks @amakhrov  for  #622. 
That PR is something we will include in next release for sure. As you mentioned, it should not assume that all Fetch API implementations will reject with a particular error type.
