### ISSUE TITLE
Localhost mode does not work with Redis Synchronizer

### ISSUE THREAD

**Issue by nicolaszein** [splitio/javascript-client#669]
[Accordingly to the documentation](https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK#consumer-mode), in order to use the Split Synchronizer with de NodeJS SDK, we need to call `getTreatment` function asynchronously because of the Redis. 

I'm trying to use the `then catch` syntax like so:

```js
client
  .getTreatment('user_id', 'my-feature-comming-from-redis')
  .then(treatment => {
    // do something with the treatment
  })
  .catch(() => false)
```

And in order to test this code, I'm trying to use the [Localhost mode](https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK#localhost-mode). However, because localhost mode uses in-memory storage, which is synchronous, my tests throw ` splitClient.getTreatment(...).then is not a function`.

To bypass this problem I'm using the `try catch` syntax, but it would be better to use the `then catch` syntax.

Is there a way to use localhost mode with async code? 🤔

**Comment by chillaq** [comment]
Hi @nicolaszein , If you wrap the SDK getTreatment in async function, then use that function with then and catch, it does work, see code sample below:

const path = require('path');
const SplitFactory = require('@splitsoftware/splitio').SplitFactory;

async function createSplitClient() {
    const SplitObj = SplitFactory({
        core: {
              authorizationKey: 'localhost'
        },
        startup: {
              readyTimeout :10
        },
        features: path.join(__dirname, 'first.yaml'),
        debug: true
    });
    const client = SplitObj.client();
    await client.ready()
    console.log("SDK is ready");
    return client
}
async function getSplitTreatment(userKey, splitName) {
    let splitClient = await createSplitClient()
    return await splitClient.getTreatment(userKey, splitName);
}
getSplitTreatment("user", "first_split").then((treatment)=> {
    console.log("treatment: "+treatment)
})
.catch(() => {
    console.log("SDK exception")
});
