### ISSUE TITLE
Update documentation to use splitClient.Ready()

### ISSUE THREAD

**Issue by prasanthlouis** [splitio/javascript-client#716]
Hi there,
Just curious whether it'd be useful to provide documentation on the official website about the split client. ready() function:
https://github.com/splitio/javascript-client/blob/e14e3d99f0a99b315996e6de69d1fddb24b24db9/types/splitio.d.ts#L432-L450

I couldn't find it on the official website, but I found it while poking through the source code. Is it frowned upon to use this function? It seems more flexible than the standard SDK emitted events: https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK#basic-use

**Comment by chillaq** [comment]
Hi @prasanthlouis , the client.ready() is a promise that will resolve once the SDK is ready. You are correct it is not in the documentation, however, it is one of the fixes documented in CHANGES.txt file.
We also suggest using it in this KB: https://help.split.io/hc/en-us/articles/360053286091-Javascript-SDK-Does-SDK-READY-event-fire-only-once-

Thanks
Bilal
