### ISSUE TITLE
Getting `only default export is available soon` under Webpack5

### ISSUE THREAD

**Issue by yuanjieliu-myob** [splitio/javascript-client#729]
Hey, I'm using webpack5 on my project, I'm running the following error.

**ERROR** in ./node_modules/@splitsoftware/splitio/es/utils/settings/index.js 127:87-94
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)

@ ./node_modules/@splitsoftware/splitio/index.js 5:0-47 32:17-32

Here is a same issue on StackOverflow,
https://stackoverflow.com/questions/64993118/error-should-not-import-the-named-export-version-imported-as-version

Could you take a look at this issue?

Thanks.

**Comment by hbqdev** [comment]
@yuanjieliu-myob 

Can you please confirm the version of your SDK?

Thank you and Regards

**Comment by yuanjieliu-myob** [comment]
Hey @hbqdev,
We are using @splitsoftware/splitio@10.12.0. 
Thanks.

**Comment by hbqdev** [comment]
Hi @yuanjieliu-myob ,

Can you please share with us the webpack the config so we can test on our side?

Regards,

**Comment by hbqdev** [comment]
Hi @yuanjieliu-myob 

Since we haven't heard back from you in awhile, we will close this issue for now, please update your SDK version and try again and let us know.

Regards
