### ISSUE TITLE
Always got control

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [splitio/javascript-client#733]
I tried
```
      const newTreatments2 = client.getTreatment('abcde', 'database_split', { use: 'a'})
``

but I always got 
```
[ERROR] splitio => getTreatment: attributes must be a plain object.
```

It worked only if I pass the key during initialization
```
const factory: ISDK = SplitFactory({
  core: {
    authorizationKey: 'YOUR_SDK_KEY',
    key: 'dummy',
  },
  debug: true,
});
```

**Comment by hbqdev** [comment]
Hi @LieAlbertTriAdrian 
This is expected, you must pass in the key when you initialize the SDK, the API key will let the client intanciated correctly for you to get treatments.

Regards

**Comment by hbqdev** [comment]
Hi @LieAlbertTriAdrian 
I'm closing this issue for now, let us know if you have further questions or concerns.

Regards
