### ISSUE TITLE
ioredis library being bundled with Browser SDK

### ISSUE THREAD

**Issue by seanzx85** [splitio/javascript-client#735]
Hi 👋 

We are doing some bundle analysis and it looks like ioredis is being bundled with the web browser webpack build.  This is doubling the packaged size of the spiltio code in the bundle.

It looks like this issue might be the cause: https://github.com/splitio/javascript-client/issues/400

Package.json - https://github.com/splitio/javascript-client/blob/development/package.json#L42

Is there a work around or documentation published on how splitio expects  browser to exclude this module?  Or do we need to mark it as external for webpack?

**Comment by seanzx85** [comment]
Some more digging revealed that if I remove the javascript client library and import the SDK through the react client directly I can avoid the double import with ioredis


No double load:
```
import { SplitSdk } from "@splitsoftware/splitio-react";
```

Original import
```
import { SplitFactory } from "@splitsoftware/splitio";
```

While this library may work int he browser it isn't really optimized, due to the requirements of shipping IORedis to the browser.

**Comment by agustinona** [comment]
Hi @seanzx85 thanks for the feedback. We'll look into this. If you are looking to minimize the bundle size required to run the Split SDK in the browser, you may be interested in running our [Browser SDK](https://help.split.io/hc/en-us/articles/360058730852-Browser-SDK) instead which is optimized for this purpose.

**Comment by seanzx85** [comment]
@agustinona  it maybe as simple as updating this to remove the browser as a supported environment and link to the browser sdk repo.

https://github.com/splitio/javascript-client#compatibility

**Comment by agustinona** [comment]
@seanzx85 Could you review your webpack build target? It seems webpack is resolving to `main` instead of `browser`, which would not import ioredis, here: https://github.com/splitio/javascript-client/blob/development/src/factory/package.json

**Comment by seanzx85** [comment]
`web` is the browser specific target and the default.  https://webpack.js.org/configuration/target/. We didn't defined a target since we are using web. I can upload a sanitized version of our webpack if that would help.

**Comment by agustinona** [comment]
Hi @seanzx85 I apologize for the late response.

Yes, that would be helpful for me to attempt to reproduce this on my end. If you have a sample project to repro this behavior it would be even better.

**Comment by seanzx85** [comment]
Here is our sanitized webpack abd babel.config.js.

babel.config.js
```
{
  "targets": "> 0.25%, not dead"
}

```
Webpack:

```
{
  "entry": {
    "sanitized": "/sanitized/frontend/packages/sanitized/src/components/loader/loader.ts"
  },
  "plugins": [
    {
      "profile": false,
      "modulesCount": 5000,
      "dependenciesCount": 10000,
      "showEntries": true,
      "showModules": true,
      "showDependencies": true,
      "showActiveModules": false
    },
    {
      "test": {},
      "outputCss": true,
      "allowRuntime": false,
      "childCompiler": {}
    },
    {
      "config": {
        "path": ".env.testint",
        "prefix": "process.env.",
        "systemvars": true
      }
    },
    {
      "patterns": [
        { "from": "public/locales", "to": "locales" },
      ],
      "options": {}
    }
  ],
  "devtool": "source-map",
  "module": {
    "rules": [
      { "test": {}, "use": ["style-loader", "css-loader"] },
      { "test": {}, "type": "asset/inline" },
      {
        "test": {},
        "exclude": [{}],
        "use": [
          {
            "loader": "babel-loader",
            "options": {
              "babelrc": true,
              "presets": [
                "@babel/preset-typescript",
                ["@babel/preset-react", { "runtime": "automatic" }],
                ["@babel/preset-env", { "modules": false }]
              ]
            }
          }
        ]
      }
    ]
  },
  "resolve": {
    "extensions": [".tsx", ".ts", ".js"],
    "preferAbsolute": true,
    "modules": [
      "/sanitized/frontend/packages/sanitized/src",
      "node_modules"
    ],
    "alias": { "@": "/sanitized/frontend/packages/sanitized/src" }
  },
  "output": {
    "library": "Sanitized",
    "libraryTarget": "umd",
    "filename": "[name].js",
    "libraryExport": "default",
    "globalObject": "this",
    "path": "/sanitized/frontend/packages/sanitized/dist/testint",
    "publicPath": "http://localhost:3002/"
  },
  "optimization": {
    "minimize": true,
    "concatenateModules": true,
    "usedExports": true,
    "flagIncludedChunks": true,
    "mergeDuplicateChunks": true,
    "removeAvailableModules": true,
    "minimizer": [
      {
        "options": {
          "test": {},
          "extractComments": true,
          "parallel": true,
          "minimizer": {
            "options": {
              "output": { "comments": false },
              "mangle": true,
              "compress": true,
              "sourceMap": true
            }
          }
        }
      }
    ]
  },
  "infrastructureLogging": { "level": "verbose" },
  "mode": "production"
}
```
