### ISSUE TITLE
JSON sent over the wire is uncompressed

### ISSUE THREAD

**Issue by cltnschlosser** [splitio/javascript-client#742]
Looks like the backend for `https://sdk.split.io/api/splitChanges?since=-1` doesn't support compression. The browser is correctly setting the `accept-encoding: gzip, deflate, br` header. This is a JSON payload that could benefit from being compressed over the network.

**Comment by agustinona** [comment]
Hi @cltnschlosser,

I've submitted this as a feature request on your behalf for consideration by our targeting delivery team. Since this is not directly related to the JS SDK itself, I'm closing this as an issue.

**Comment by agustinona** [comment]
@cltnschlosser just wanted to let you know our team has enabled compression for our API so you will see compressed responses over the next few days as the uncompressed ones expire from our CDN.

Thanks for raising attention to this!

**Comment by cltnschlosser** [comment]
Thanks, to everyone involved, for the quick turn around! Seeing a massive improvement here. Payload size reduced 14x :)
