### ISSUE TITLE
[DOC] How to use conditions/attributes when using localhost mode?

### ISSUE THREAD

**Issue by lopes-gustavo** [splitio/javascript-client#743]
I couldn't find in the documentation how to use attributes in the yaml file.
Is it even possible?
Thanks

**Comment by agustinona** [comment]
Hi @lopes-gustavo ! It is not currently possible to use attributes for targeting when running the SDK in localhost mode. The YAML file allows to set feature flag names, treatment names, allowlists and dynamic configurations only.

**Comment by agustinona** [comment]
@lopes-gustavo One additional comment: while there is no ETA for this yet, the localhost mode will in the future allow you to provide a JSON with fully featured feature flag definitions that will allow you to use the full targeting complexity that is available through the web console. This is already implemented in some other languages, and you can check those to get an idea of what the new functionality is: https://help.split.io/hc/en-us/articles/360020405151-Java-SDK#json
