### ISSUE TITLE
Avoid usage of "unload" event entirely

### ISSUE THREAD

**Issue by WillsB3** [splitio/javascript-client#759]
I've just been integrating Split's SDK into one of our applications and in doing so have been notified by our performance testing CI job that our pages now register an `unload` event handler as a result of integrating Split. This causes our Lighthouse CI job to fail as there is an assertion that checks that there are no `unload` event handlers registered.

The `unload` event should be avoided ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event)) in modern browsers because it prevents browsers from being able to add the page to its back/forward cache which helpers improve navigation performance. See [this web.dev documentation](https://developer.chrome.com/articles/page-lifecycle-api/#the-unload-event) for further details which states _"Never use the unload event on modern browsers."_

In searching for previous issues related to this I came across https://github.com/splitio/javascript-client/issues/594, in which it was stated that:

> the SDK now relies on visibilitychange and pagehide events, **instead of unload**, to extend the coverage of mobile and desktop browsers.

However I can still see the `unload` event being registered in DevTools and I can also see the event listener being registered in [the source on GitHub](https://github.com/splitio/javascript-commons/blob/development/src/listeners/browser.ts#L55).

Can the `unload` event handler be removed, or only added where required for legacy browsers?

**Comment by EmilianoSanchez** [comment]
Hi @WillsB3 ,

Thank you for bringing this up. We decided to follow your advice and will remove the 'unload' event handler. The SDK only relies on the 'pagehide' and 'visibilitychange' events as recommended. The change will be reflected in the next release.

**Comment by EmilianoSanchez** [comment]
Closing the ticket, since we have included the suggestion in the latest version [10.23.1](https://www.npmjs.com/package/@splitsoftware/splitio/v/10.23.1)
