### ISSUE TITLE
Node server hangs when running browser API key

### ISSUE THREAD

**Issue by jacobarriola** [splitio/javascript-client#768]
I recently ran into some issues when accidentally running a browser type API in a server environment (Node). Unfortunately, Split didn't seem to gracefully fail and my app just hung in a loading state, so I'd love to know if there's something wrong in my setup.

## Repro steps
* Next.js, v13.5, app router
* Use a production client-type API key instead of a server-type API key
* In a React Server Component, get a treatment via `getTreatment()`

## Expected results
* Split should fail and return `control` on the treatment request
* Page should still load as the request fulfills

## Actual results
* Split hangs 
* The page stays in an infinite loading state

According to the [docs](https://help.split.io/hc/en-us/articles/360025918571-Troubleshooting#factory-instantiation-validation), when this type of error occurs, any calls to `getTreatment` will return a control.

Repo to reproduce the issue (minus the API key): https://codesandbox.io/p/sandbox/serene-field-v8lr7s?file=%2Fapp%2Fpage.tsx%3A13%2C31

**Comment by EmilianoSanchez** [comment]
Thank you @jacobarriola  for flagging the error. 

We will include a fix for it on next release. 

As expected, if a client-side (browser) SDK key is provided when running the SDK in NodeJS, it will emit the SDK_READY_TIMED_OUT event, and so, the `client.ready()` promise will reject.

**Comment by EmilianoSanchez** [comment]
Version 10.24.0 of `@splitsoftware/splitio` has been finally released, which includes the fix for this issue.
I will close the issue now. 

CC: @jacobarriola
