### ISSUE TITLE
Node.js SDK fails silently if wrong key type is used with segments

### ISSUE THREAD

**Issue by redbugz** [splitio/javascript-client#789]
We accidentally used the client-side key instead of the server-side key in our Node SDK. This worked fine for many years and went undetected until we used a segment for the very first time, then this code ran for the first time in all of our Node SDKs:

https://github.com/splitio/javascript-commons/blob/7a81cd2f4acb1d849e54dc6671d7078321790ba8/src/sync/polling/updaters/segmentChangesUpdater.ts#L100

Which killed all our Node SDKs at once across all our apps, but it did not log any errors in any of our applications, it just silently failed and started returning control for all flags. We could not see the actual cause of the failure until we enabled the debug logging flag, then the error message finally appeared and the simple fix of using the right key type suddenly became apparent.

The error logging for that failure should not depend on the debug logging flag, that error should log very obviously so it's clear why the Node SDK is failing. Perhaps even better would be to warn or fail sooner when using the wrong key type in an obvious way to help detect the mistake earlier than when segments finally trigger.

**Comment by agustinona** [comment]
Hi @redbugz thank you for the feedback! I'm submitting this as an RFE for our team to take into consideration for future releases.

**Comment by redbugz** [comment]
https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK#logging

I would have expected that ERROR would be the default logging level, but it appears that NONE is the default level?
https://github.com/splitio/javascript-commons/blob/7a81cd2f4acb1d849e54dc6671d7078321790ba8/src/logger/index.ts#L37

We will update our code to at least log at the ERROR level

**Comment by agustinona** [comment]
@redbugz Yes, our SDKs use log level None as the default for two main reasons. The first is we don’t want to pollute our customers’ apps by displaying information that users don’t need to see. Other than that, some of our customers use paid logging tools with limited quotas and Split SDKs logging by default may inadvertently push them over their quota and cause issues. Each SDK has their own Logger section page that provides guidance on how to set the desired logging level for each customer’s needs.

Nevertheless, we are capturing this feedback to analyze if this approach should be modified in the future based on demand.
