### ISSUE TITLE
Localhost clients should allow feature flag `trafficType` setting

### ISSUE THREAD

**Issue by pm0u** [splitio/javascript-client#792]
When testing our split implementation, I am trying to use Localhost mode as recommended. We have 2x clients per https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#instantiate-multiple-sdk-clients one for a device identifier and another for a user identifier.

We would initialize those clients similar to the following:
```ts

const splitSDK = SplitFactory({
  core: {
    authorizationKey: '',
    key: 'DEVICE_ID',
    trafficType: 'device'
  }
})

```

We have logic similar to the following in place

```ts
const splitView = splitSDK.manager().split(featureName)

let clientForSplit;

if (splitView.trafficType === 'user' && weHaveUserId()) {
  clientForSplit = splitSDK.client('USER_ID', 'user')
} else if (splitView.trafficType === 'device') {
  clientForSplit = splitDeviceSDK.client('DEVICE_ID', 'device')
}

if (!clientForSplit) return

return clientForSplit.getTreatment(featureName)
```

And for testing

```ts
import { SplitFactory } from '@splitsoftware/splitio'
jest.mock('@splitsoftware/splitio')

const TestSplitFactory = (settings: SplitIO.IBrowserSettings) =>
  jest.requireActual('@splitsoftware/splitio/client').SplitFactory({
    ...settings,
    core: {
      ...settings.core, // this would include the `trafficType` per above implementation
      authorizationKey: 'localhost'
    },
    features: MOCK_TESTING_FEATURES
  })

jest.mocked(SplitFactory).mockImplementation(TestSplitFactory)
```

In this situation, if I attempt to use localhost mode in a testing environment, the `trafficType` returned from manager is always `localhost` and this logic fails. 

If this feature is intended to be used strictly for testing and local development, this is completely unhelpful - we should not care that this is a localhost client since this is only ever intended to be used as a stub for a real client. I don't see how `localhost` is a traffic type - it does not seem to fit the [definition of "traffic type"](https://help.split.io/hc/en-us/articles/360019916311-Traffic-type) _The traffic type denotes the nature of the keys that are passed to getTreatment for that feature flag_. Also, this information is already exposed on the `mode` property of the localhost SDK settings if it was for some reason needed to be known at runtime.

https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#localhost-mode

> For testing,...

**Comment by agustinona** [comment]
Hi @pm0u I believe you may be mixing up some traffic type concepts here. The traffic type you specify in the factory config (as well as the one you specify when instantiating/getting a client: `.client(key,trafficType)`) only determines the traffic type that will be used for that client (or the default client in the case of the TT specified in the factory config) when tracking an event **without** specifying a traffic type. This has no effect on anything returned by the Split Manager, including feature flag representations. The traffic type in there corresponds to the traffic type of the feature flag itself, which is specified in the FF's definition.

What you are seeing comes from a limitation of the syntax currently used when defining your feature flags in localhost mode, which doesn't allow to specify the traffic type. In the future you'll be able to provide full fledged definitions through a JSON, including the FFs' traffic types. If interested, you can see how this works in our docs for other SDKs where this is already implemented: https://help.split.io/hc/en-us/articles/360020405151-Java-SDK#json.

However, from what I can see this shouldn't represent an issue for your particular use case. When working in localhost mode in most cases you don't really care about the key being passed (unless you are including individual targets in your local FF defs), so you could just provision a third clause for localhost specifically. Note that in localhost mode you wouldn't really be posting events, so specifying 'localhost' as the traffic type, while not a valid traffic type, is not an issue and will prevent any issues with track calls without a traffic type in your code.
```
if (splitView.trafficType === 'user' && weHaveUserId()) {
  clientForSplit = splitSDK.client('USER_ID', 'user')
} else if (splitView.trafficType === 'device') {
  clientForSplit = splitDeviceSDK.client('DEVICE_ID', 'device')
} else if (splitView.trafficType === 'localhost') {
  clientForSplit = splitDeviceSDK.client('LOCALHOST_ID', 'localhost')
}
```

Would this work for you?

**Comment by pm0u** [comment]
it would "work" in that it would fix our testing but we would prefer to not commit this code to production as it's essentially adding a dead code path just to accommodate testing.

> The traffic type in there corresponds to the traffic type of the feature flag itself, which is specified in the FF's definition.

This is my issue - we are not defining the traffic type when we mock features and Split's SDK is filling them in for us in a non-desirable way. When is the improved JSON feature definition expected to be available in the JS SDK?

**Comment by pm0u** [comment]
I updated the title to better reflect the specific area where the issue lies
