### ISSUE TITLE
Tslib dependency not declared

### ISSUE THREAD

**Issue by polson136** [splitio/javascript-client#795]
As you can see here, this package require()s tslib

![image](https://github.com/splitio/javascript-client/assets/2353281/e93d19e8-0a7e-49d8-9444-37ef8aee7773)

but tslib is not in the package's dependencies

![image](https://github.com/splitio/javascript-client/assets/2353281/ecd7badb-6150-49c4-83dc-47d1a74d9525)

In my case, it's causing issues because we use yarn pnp, which requires all dependencies' dependencies to be explicitly declared, but it would also cause issues if someone somehow manages to have a project without any existing dependency on tslib. If tslib ever releases a v3, things could also get rather interesting.

The [react client](https://github.com/splitio/react-client) also has this problem.

**Comment by EmilianoSanchez** [comment]
Hi @polson136 

Thank you for raising this issue. As you suggested, we will explicitly add `tslib` as a runtime dependency in the upcoming releases of the JS SDK, React SDK, etc. Relying on it as a transitive dependency through `@splitsoftware/splitio-commons` is insufficient.

We do not have an ETA for the next releases, but in the meantime, consider installing `tslib@2` manually to resolve your issue.

**Comment by EmilianoSanchez** [comment]
Also @polson136, if you can share what version of Yarn you are using, it would be appreciated. Thanks

**Comment by EmilianoSanchez** [comment]
`@splitsoftware/splitio` version 10.25.2 and `@splitsoftware/splitio-react` version 1.11.1 have been released, which include the change suggested by @polson136 .

**Comment by polson136** [comment]
The fix works for me, thanks!
