### ISSUE TITLE
ioredis is unmaintained

### ISSUE THREAD

**Issue by jamesarosen** [splitio/javascript-client#799]
This package has a hard runtime dependency on [ioredis](https://github.com/redis/ioredis), but that package hasn't had a release in over a year. Redis has since changed its licensing. There are hundreds of open issues.

Even if you want to keep `ioredis` as the default, it would be great to be able to swap in the official [node-redis](https://github.com/redis/node-redis) package using `optionalDependencies`.

See, for example, https://github.com/taskforcesh/bullmq/issues/2490

**Comment by agustinona** [comment]
Hi @jamesarosen thanks for the suggestion. As pointed out in the thread you linked, both libraries have a similar amount of open issues and there doesn't seem to be any clear indication that [node-redis](https://github.com/redis/node-redis) is more actively maintained, but our team will revisit this in a future dependency revision.
