### ISSUE TITLE
Version 9.2.0 contains untranspiled ES6 code

### ISSUE THREAD

**Issue by Rowno** [splitio/javascript-client#80]
Version 9.2.0 introduced a new dependency (logplease) which contains untranspiled ES6 code. 

This is a breaking change.

See here:
https://github.com/haadcode/logplease/blob/4a9aa0bf4e5d6130fd84e3ba87c48f7b440d805b/package.json#L5
https://github.com/haadcode/logplease/blob/4a9aa0bf4e5d6130fd84e3ba87c48f7b440d805b/src/index.js

**Comment by patricioe** [comment]
Thank you @rowno for bringing this to our attention. We'll address it as soon as we can.

**Comment by goldensun8891** [comment]
@Rowno thanks for raising this and apologies for any inconvenience this has caused! Our team has pushed out a canary version that should resolve this issue: npm install -S @splitsofware/splitio@9.2.1-canary.0

Let us know if you continue to see issues!

**Comment by stephenmathieson** [comment]
I'd like to point out that we (Segment) _tried_ updating to version 9.2.0 in regards to an email sent by you guys:

<img width="1191" alt="screen shot 2017-05-19 at 10 52 20" src="https://cloud.githubusercontent.com/assets/571265/26260219/4159f802-3c81-11e7-9f64-c83fabbbb4a3.png">

Had we rolled out the change without testing it fully, this would have been the second outage split.io caused us in 15 days. To say the least, I'm not impressed.

**Comment by goldensun8891** [comment]
Hi Stephen, What you're saying is very fair and this is not the experience we aim to give to our customers. We recognize the enormous amount of trust you are putting in our system by using us to control your customer experience. Our team is revamping our internal processes now to make sure that this does not happen again.

**Comment by stephenmathieson** [comment]
Thanks Kevin, that's great to hear. Please keep us posted!

**Comment by goldensun8891** [comment]
@stephenmathieson and @Rowno, version 9.2.1 is now fully published. you should no longer see issues with untranspiled ES6 code
