### ISSUE TITLE
Possible memory leak on impressions tracking

### ISSUE THREAD

**Issue by leeeomaaax** [splitio/javascript-client#803]
lib version: 10.25.2 (but this was also happening on version 10.23.1)
node version: 18

- Our servers seems to be experiencing a memory leak on the getTreatment function. (similar to [this issue](https://github.com/splitio/javascript-client/issues/503))
- Memory goes up really slowly, so it's super hard to reproduce locally
- Exploring the memory profiler in prod, we found some data pointing to the [track method inside the javascript-common library](https://github.com/splitio/javascript-commons/blob/development/src/trackers/impressionsTracker.ts#L29)

<img width="1523" alt="Screenshot 2024-04-23 at 16 39 24" src="https://github.com/splitio/javascript-client/assets/17117431/a7128912-502a-4951-9cfb-0e2341c2041a">

- every time the lines going up drop, means we did a new deploy. deploys in this graph were done 1 week apart so I don't believe this is the regular impression queue going up before being flushed.
- lines that are constantly going up vary, but they are always one of the following: [Track method](https://github.com/splitio/javascript-commons/blob/development/src/trackers/impressionsTracker.ts#L29), hash128x86 method, [process method](https://github.com/splitio/javascript-commons/blob/development/src/trackers/strategy/strategyOptimized.ts#L20) (all methods from javascript-commons)

<img width="738" alt="Screenshot 2024-04-23 at 16 43 55" src="https://github.com/splitio/javascript-client/assets/17117431/4cadd8d3-8d63-4f45-8577-edcfc2895c18">

- flamegraph of memory allocation

--
- is there a way I can disable impressions tracking on the node SDK? 
- can you guys take a look and let me know if I'm missing something?

**Comment by radiantstatic** [comment]
@leeeomaaax - my company is seeing similar behavior. We even went so far as to set up split synchronizer to alleviate some of the pressure, but unfortunately did not resolve the issue. Would love to hear from Split team if there is something worth fixing.

![Screenshot 2024-04-24 at 10 43 50 PM](https://github.com/splitio/javascript-client/assets/1668054/cfcac5bb-e985-4a45-b564-c159270cd4c3)

**Comment by leeeomaaax** [comment]
hey @radiantstatic , we've opened a support ticket with the Split team and they suggested disabling the impressionsMode.
We've tested and it seems that the leak is gone (or at least it is at a really low level).

<img width="1599" alt="Screenshot 2024-05-03 at 12 30 23" src="https://github.com/splitio/javascript-client/assets/17117431/4ba02d99-79ca-4244-9d8d-0d27af8e5ebf">

``` typescript
sync: {
  impressionsMode: 'NONE',
},
```

**Comment by leeeomaaax** [comment]
Thank you for following up on this @EmilianoSanchez!
It makes sense now why I wan't able to reproduce it locally -> I was applying load on the getTreatment call with always the same user key/flag.

**Comment by EmilianoSanchez** [comment]
Yes. That makes sense @leeeomaaax .

I cannot 100% guarantee there is not a memory leak, but it's probably related to that cache.

<img width="1174" alt="LRUCache-full" src="https://github.com/splitio/javascript-client/assets/3229776/14f128f5-cd31-447e-be9a-9f529c9cab18">

Using the Chrome dev tools, it seems that the LRUCache size is around 114.6 MBs when it is full (the Retained size column in the screenshot, which is in bytes).
