### ISSUE TITLE
Nodejs getTreatment always returns control

### ISSUE THREAD

**Issue by sidhinged** [splitio/javascript-client#805]
Hi,
    I am trying to use SplitIO SDK in an edge function and following the documentation here - https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK.
   
   The auth key is a server side API key. I am not using `key` in the Factory init.
    In the UI, for a Feature Flag (say "FF_sid"), I have Individual Target set as 'on' for a user 'sid'.
  
   Here is the code
  
 
      const factory: SplitIO.ISDK = SplitFactory({
             core: {
                     authorizationKey: splitAuthKey
                 },
             debug: true, 
       });

        const client: SplitIO.IClient = factory.client();
        await client.ready();

        console.log(client.getTreatment("sid, 'FF_sid'));

   It always returns "control" instead of "on".

   Also I am always getting the error 
```
       [ERROR] splitio => getTreatment: you passed an invalid key. It must be a non-empty string.
       [ERROR] splitio => getTreatment: you passed an invalid feature flag name. It must be a non-empty string.   
```

   What am I missing?

Thanks in advance,
Sid

**Comment by EmilianoSanchez** [comment]
Hi @sidhinged ,

I assume you are importing the library with `import { SplitFactory } from '@splitsoftware/splitio'` (or with CommonJS as `const { SplitFactory } = require('@splitsoftware/splitio')`). 

So, if your code is running in NodeJS, it will use the server-side or multi-tenant API described here  https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK., where you need to provide the user key as first argument in the `getTreatment` method calls.
But if your code is running in the Browser (like a Web UI), the API that it is using is the so-called client-side or single-tenant API, which is described at https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK and where you need to provide the user key in the SDK configuration or when calling the `factory.client` method.

So, if your code will be executed in a Browser-like environment, it should be refactored as follows:

```javascript 
import { SplitFactory } from '@splitsoftware/splitio'

  const factory: SplitIO.ISDK = SplitFactory({
         core: {
                 authorizationKey: splitAuthKey, // Preferable use a client-side SDK key, although a server-side SDK key will work too
                 key: "sid",
             },
         debug: true, 
   });

    const client: SplitIO.IClient = factory.client();
    await client.ready();

    console.log(client.getTreatment('FF_sid'));
```

Regards

**Comment by sidhinged** [comment]
Thanks @EmilianoSanchez. I will continue conversation in a support ticket to explore solutions.
