### ISSUE TITLE
splitio client throws `undefined is not a function` error for node 0.x

### ISSUE THREAD

**Issue by stephenotalora** [splitio/javascript-client#97]
The issue is explained in great detail here: https://github.com/splitio/javascript-client/pull/96 can some-one please help or approve/merge pr? the fix is very simple and I have tested as well as run unit test to verify issue is fixed.

**Comment by patricioe** [comment]
Thank you for submitting the issue. We'll take a look.

What version of node are you running specifically just to have more context.

**Comment by stephenotalora** [comment]
@patricioe I'm running an older version of node for production legacy code. Any node version bellow 4.x will break and won't allow the sdk to initialize properly. when I found the bug I was running on node v0.12.18 but the same issue is found on node v0.10.33 and v0.10.22.

**Comment by NicoZelaya** [comment]
Hi @stephenotalora! First of all, thank you for not just reporting the issue but also taking the time to provide a good explanation and even issue a PR!

I've just released a canary version (release candidate) and I wanted to ask if you would be so kind to give it a try yourself. 
Version: 9.3.2-canary.0
PR (based on yours): https://github.com/splitio/javascript-client/pull/98

If all goes well this should be out by the end of today.

Thanks in advance!

**Comment by stephenotalora** [comment]
@patricioe not a problem at all, glad to contribute. I am having a look now and will get back to you shortly.

**Comment by stephenotalora** [comment]
@NicoZelaya 🎉  looks like it works great!  `Event.SDK_READY` now fires as expected on node 0.x.

**Comment by NicoZelaya** [comment]
This is great to hear! I'll let you know as soon as the stable version is out.

**Comment by stephenotalora** [comment]
@NicoZelaya thank you very much!

**Comment by stephenotalora** [comment]
@NicoZelaya are we still on target for EOD?

**Comment by NicoZelaya** [comment]
@stephenotalora version 9.3.2 is out! Lmk if it works for you and I'll close the issue. Thanks for your patience!

**Comment by NicoZelaya** [comment]
Closing the issue now, fixed on version [9.3.2](https://github.com/splitio/javascript-client/releases/tag/9.3.2)
